# Generated by Django 4.0.4 on 2022-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surame', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('cover_path', models.URLField()),
                ('cast', models.ManyToManyField(related_name='movies_as_actor', to='movies.person')),
                ('director', models.ManyToManyField(related_name='movies_as_director', to='movies.person')),
                ('genre', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
    ]
