# Generated by Django 4.0.4 on 2022-05-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='surame',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default='1973-01-01'),
            preserve_default=False,
        ),
    ]
