# Generated by Django 4.0.4 on 2022-05-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_surame_person_surname_person_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
        migrations.AddField(
            model_name='person',
            name='name_surname',
            field=models.CharField(default='nome', max_length=50),
            preserve_default=False,
        ),
    ]
