# Generated by Django 4.0.4 on 2022-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_director_movie_directors_remove_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added_date',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
