# Generated by Django 4.0.4 on 2022-05-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
    ]
