# Generated by Django 4.0.4 on 2022-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover',
            field=models.ImageField(default=None, upload_to='imgs/covers/'),
        ),
    ]
