# Generated by Django 4.0.4 on 2022-05-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img_path',
            field=models.URLField(default='imgs/profiles_imgs/default.jpg'),
        ),
    ]
