# Generated by Django 4.0.4 on 2022-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img_path',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default=None, upload_to='imgs/profileImgs/'),
        ),
    ]
